### ISSUE TITLE
iOS VerticalBlueprintLayout add item question

### ISSUE THREAD

**Issue by Karthus1110** [zenangst/Blueprints#113]
![8F0409E475AABDFE5C0FA6AE021EDB65](https://user-images.githubusercontent.com/13864988/61107008-61e3da80-a4b1-11e9-8b47-54e06a98b7fd.png)

![image](https://user-images.githubusercontent.com/13864988/61107314-3a414200-a4b2-11e9-99f6-6e57a72b7ccd.png)

prefer add left line,On the right side of the blank

**Comment by zenangst** [comment]
Hey @Karthus1110, if I understand you correctly you want the items to fill the empty space on the right? Mind sharing the configuration of your layout? Or even better, a dummy project would be awesome to see if this is a configuration issue or a bug in the layout.

**Comment by Karthus1110** [comment]
@zenangst here is the configuration 
![image](https://user-images.githubusercontent.com/13864988/61339633-47bf4900-a871-11e9-9424-c82c735186f5.png)
![image](https://user-images.githubusercontent.com/13864988/61339649-560d6500-a871-11e9-8ad0-2318c767eb30.png)

I don't know if I misconfigured it

**Comment by zenangst** [comment]
@Karthus1110 thanks for that, I’m currently on vacation with my family but I’ll look into this when life allows. @christoff-1992 do you have some spare time to test this out? If not then I’ll check it in a weeks time or so.

**Comment by christoff-1992** [comment]
@zenangst - Apologies only just seen the messages, been a bit busy recently but will take a look as soon as I can.

**Comment by Karthus1110** [comment]
Thanks for your reply
i have try the code you give, but it still not work
The question appears when load more, you can try to load 3-5 pages, it will show
here is the demo 
[PixHall.zip](https://github.com/zenangst/Blueprints/files/3434398/PixHall.zip)

**Comment by christoff-1992** [comment]
Ahh it's not the layout, it's the fact that you have run out of images in the collection, you don't download images until the threshold is hit. You need to adjust the polling of new images to take into account the y position of the last cell. If you keep scrolling down you will see that the application downloads additional images and the cells fill up the available space.

**Comment by Karthus1110** [comment]
I konw i have run out of images in collection. But i think the correct present is this two line should be filled more evenly.

**Comment by christoff-1992** [comment]
@Karthus1110 - Il take a proper look as soon as I get time :)

**Comment by christoff-1992** [comment]
@Karthus1110 - Sorry for the late reply, it hasn't been such a simple fix and myself and @zenangst have been looking into improving the layout.

![2019-08-14 15 48 19](https://user-images.githubusercontent.com/12499390/63030934-1acf7780-beab-11e9-8647-98360e3653ce.gif)

Does this look better?

**Comment by Karthus1110** [comment]
@christoff-1992 Thanks very much.It's looked really nice now.

**Comment by christoff-1992** [comment]
@Karthus1110 - Take a look at the latest release 😁 https://github.com/zenangst/Blueprints/releases/tag/0.12.1 can you let us know if it resolves your issues. We have tested against the demo project and it looks to be fixed.

**Comment by christoff-1992** [comment]
Closing issue as this has been reworked @Karthus1110 - feel free to re-open if there are still issues with this.
