### ISSUE TITLE
fixed width in horizontal scrolling

### ISSUE THREAD

**Issue by zishanj** [zenangst/Blueprints#114]
Is it possible to fix the width to constant value in `HorizontalBlueprintLayout`. I have tried using `estimatedItemSize` and width constraint on `contentView` but its getting override by the library.

**Comment by zenangst** [comment]
@zishanj hey mate, try setting `itemSize` instead of `estimatedItemSize` using this initializer: https://github.com/zenangst/Blueprints/blob/master/Sources/Shared/Core/HorizontalBlueprintLayout.swift#L24

**Comment by zishanj** [comment]
That gives me error of `private function`.

**Comment by zishanj** [comment]
Sorry, it works with _different number_ of parameters https://github.com/zenangst/Blueprints/blob/master/Sources/Shared/Core/HorizontalBlueprintLayout.swift#L95. Thanks
