### ISSUE TITLE
Incorrect "Waterfall" layout order

### ISSUE THREAD

**Issue by alexanderkhitev** [zenangst/Blueprints#143]
Hey! Thank you for the great framework!
I tried demo project and noticed a vertical layout bug.
For instance: CollectionView contains multiple cells and two cells with index 31 and 32 which have the same Y, but the cell with index 31 is located on the right, not on the left.

Please have a look on the screenshots. 
![Screen Shot 2021-03-26 at 8 14 21 PM](https://user-images.githubusercontent.com/12511909/112662894-a5db6680-8e71-11eb-93a0-935bfbe3d880.png)
![Screen Shot 2021-03-26 at 8 15 02 PM](https://user-images.githubusercontent.com/12511909/112662900-a70c9380-8e71-11eb-9d84-c40cd0d3496f.png)
![Screen Shot 2021-03-26 at 8 15 18 PM](https://user-images.githubusercontent.com/12511909/112662905-a83dc080-8e71-11eb-85b9-f068e150aa43.png)

**Comment by alexanderkhitev** [comment]
Does framework have any settings to change it? Thanks!

**Comment by zenangst** [comment]
Hey @alexanderkhitev, nope that kind of setting does not exist right now but we are open to reviewing PR's if you'd like to improve the framework.

**Comment by alexanderkhitev** [comment]
> Hey @alexanderkhitev, nope that kind of setting does not exist right now but we are open to reviewing PR's if you'd like to improve the framework.

Ok, thank you!
