### ISSUE TITLE
Incorrect collectionView size after setting layout in viewWillTransition.

### ISSUE THREAD

**Issue by christoff-1992** [zenangst/Blueprints#15]
I am trying to update the collectionView layout after rotating the device.

I programatically calculate the number of items that are required per row based on the size of the cell and the available width of the view. However this causes the collection view width and height to behave very oddly.

The width becomes too large and the height becomes too small...

Is there a preferred approach to take? Here a sample of when I set the new layout.

```swift
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)

        coordinator.animate(alongsideTransition: nil) { [weak self] _ in
            guard let layout = self?.offlineLoginCollectionViewLayout(forWidth: size.width) else {
                Logger.log(message: "Failed to create layout", event: .verbose)
                return
            }
            self?.collectionView?.collectionViewLayout.invalidateLayout()
            self?.collectionView?.setCollectionViewLayout(layout, animated: true)
        }
    }
```

What I am trying to achieve is the following, 

The number of items are calculated based off the size of the item / the size of the available view width adding .1 to hint that other items are available. However on rotation to landscape I would like to recalculate this and show the update so that more items are visible to the user.

**Comment by zenangst** [comment]
Hey @christoff-1992, I'm guessing that both of your layouts are blueprint layouts?
I don't believe that you should have to invalidate the layout before setting a new one.
Simply setting the layout on the collection view should be enough. This is what I've done in the past when playing around with different layouts.

```swift
private func reload(with items: [Items]) {
    dataSource.reload(with: items)
    UIView.animate(withDuration: 0.3) {
      switch items.count > 1 {
      case true:
        self.collectionView.collectionViewLayout = self.pluralItemLayout
      case false:
        self.collectionView.collectionViewLayout = self.singleItemLayout
      }
    }
```

Mind sharing the configuration of your layouts then I might be able to help out more.

**Comment by christoff-1992** [comment]
Sure I have it working now, decided to switch to a vertical blueprint as it looked better and the issue stopped.

However now I have an issue where after rotating the collection view I can't scroll down past all the cells. Its as if it can't calculate the constraints correctly. The two may be related, debugging the view hierarchy doesn't appear to show any obvious issues.

Using the same code as above during the viewWillTransition. 

Thanks

```
    func profileCollectionViewLayout(forWidth width: CGFloat) -> UICollectionViewFlowLayout {
        let expectedWidth: Double = 320
        let expectedHeight: Double = 95
        let viewWidthDouble = Double(width)
        let numberOfItemsPerRow = expectedItemsPerRow(forViewWidth: viewWidthDouble, withItemWidth: expectedWidth)

        let blueprintLayout = VerticalBlueprintLayout(
            itemsPerRow: numberOfItemsPerRow,
            itemSize: CGSize(width: expectedWidth, height: expectedHeight),
            minimumInteritemSpacing: 10,
            minimumLineSpacing: 10,
            sectionInset: EdgeInsets(top: 16, left: 16, bottom: 16, right: 16),
            stickyHeaders: true,
            stickyFooters: false)

        return blueprintLayout
    }

    func expectedItemsPerRow(forViewWidth viewWidth: Double, withItemWidth itemWidth: Double) -> CGFloat {
        let numberOfItemsToBeDisplayed = (viewWidth / itemWidth).rounded(.down)
        return CGFloat(numberOfItemsToBeDisplayed)
    }
```

**Comment by christoff-1992** [comment]
@zenangst - Fixed 👍 , bit of an oversight on my part ensuring that the view is laid out after setting the collectionViewLayout has resolved the issue.

Thanks, will close the issue.

```
UIView.animate(withDuration: 0.3, animations: {
                self?.collectionView?.collectionViewLayout = layout
                self?.view.setNeedsLayout()
                self?.view.layoutIfNeeded()
            })
```

**Comment by zenangst** [comment]
@christoff-1992 ah, you solve it. That is awesome! 🚀 
If you found any other shenanigans, have any ideas for features and what not; don't hesitate to open an issue so that we can discuss it 😎 

Have a good one!
