### ISSUE TITLE
Mosaic Layout

### ISSUE THREAD

**Issue by guidev** [zenangst/Blueprints#30]
I'm having troubles understanding how the Mosaic Layout works... 

I don't understand why the first "block" isn't aligned on the right.

![simulator screen shot - iphone 8 - 2018-09-13 at 18 51 27](https://user-images.githubusercontent.com/1105813/45503074-132cbd80-b786-11e8-90bf-39aba14c1d27.png)

```swift
let mosaicLayout = VerticalMosaicBlueprintLayout(
  itemSize: CGSize.init(width: 50, height: 400),
  minimumInteritemSpacing: 15,
  minimumLineSpacing: 15,
  sectionInset: EdgeInsets(top: 15, left: 15, bottom: 15, right: 15),
  patterns: [
    MosaicPattern(alignment: .left, direction: .vertical, amount: 2, multiplier: 0.5),
    MosaicPattern(alignment: .left, direction: .horizontal, amount: 2, multiplier: 0.33),
    MosaicPattern(alignment: .left, direction: .vertical, amount: 1, multiplier: 0.5),
    MosaicPattern(alignment: .right, direction: .vertical, amount: 2, multiplier: 0.5)
])
```

**Comment by zenangst** [comment]
Hey @guidev, you might have stumbled upon a bug in the layout. To me, it looks like it applies either section inset or minimumIter item spacing twice for the items in the first section.

I'm gonna great a small sample project just to try it out, btw; thanks a lot for supplying the actual layout parameters that are causing a ruckus. It will speed up debugging a lot. I'll get back to you when I have more to share.

**Comment by guidev** [comment]
Thank you for your prompt reply!

Unfortunately, it doesn't seem fixed...

There's definitely 15px extra on the right of the first section!

<img width="349" alt="screen shot 2018-09-13 at 21 41 43" src="https://user-images.githubusercontent.com/1105813/45511653-dec4fb80-b79d-11e8-825d-da01b354db70.png">

**Comment by zenangst** [comment]
Did you modify your layout from the example you gave me? If so, could you pass me the new one?
When I tried it, it actually looked like it was rendering correctly 🤔

**Comment by zenangst** [comment]
This is the result that I get when using that configuration:

<img width="1211" alt="screen shot 2018-09-13 at 23 47 02" src="https://user-images.githubusercontent.com/57446/45517700-5a7b7400-b7af-11e8-8bea-a7dd7b390654.png">

**Comment by zenangst** [comment]
Hey @guidev, have you had time to dig into this any further?

**Comment by guidev** [comment]
Hi, here's a test project highlighting the issue.

Xcode 10 GM
Swift 4.2

https://github.com/gorillatech/Test-Mosaic

**Comment by zenangst** [comment]
@guidev thanks mate, aiming to take a stab at it later this evening (if life allows), I'll keep you posted!

**Comment by guidev** [comment]
Ok, this is weird...

I think I figured it out... I just deleted my Derived Data folder and everything works fine.
Apparently, changing the Podfile to point to the new branch wasn't enough, Xcode didn't recompile the framework but kept using the old one.

Anyhow... thank you for your amazing support!

<img width="381" alt="screen shot 2018-09-14 at 21 49 34" src="https://user-images.githubusercontent.com/1105813/45571905-17310c00-b868-11e8-84c3-16844e3e5e91.png">


There's something else I wanted to ask you... Why do I have to specify an `itemSize` for this kind of layout? If I change the width nothing changes

**Comment by zenangst** [comment]
@guidev fantastic! Yeah, there are two things that are hard when it comes to programming, naming things and caching 🤓 Super happy that you solved it!

Well, the item size is a bit confusing at times, I give you that. It should really just be a height for this collection as it is the only thing that really matters. To come completely clean, this is probably just an oversight on my part when developing the framework. I had this thought that all layouts should share similar initializers as they all derived from the same base class (`BlueprintLayout`) but... it doesn't really make that much sense as width is totally ignored. This should be fixed in the future to make the `init` method less confusing. Cheers for bringing it up because it does not make sense 🍻

**Comment by zenangst** [comment]
@guidev I've made a new release with the fix so you should update your `Podfile` to use the latest release :)
