### ISSUE TITLE
Xcode 10, swfit 4.2

### ISSUE THREAD

**Issue by boardmain** [zenangst/Blueprints#33]
hi when i try to build from xcode i have this error

Type 'UICollectionView' has no member 'UICollectionElementKindSectionHeader'

xcode 10
swift 4.2

**Comment by zenangst** [comment]
@boardmain have you updated to the latest version (0.8.0) - 
https://github.com/zenangst/Blueprints/releases/tag/0.8.0

That one should be good to go with Swift 4.2

**Comment by zenangst** [comment]
@boardmain any news on this issue? 😃

**Comment by zenangst** [comment]
Closing this issue, feel free to re-open it if it is still causing issues @boardmain
