### ISSUE TITLE
Changing the dataSource can cause the cachedItems layoutAttributes to become nil, when the updated datasource has items for section at index.

### ISSUE THREAD

**Issue by christoff-1992** [zenangst/Blueprints#40]
I have observed the following behaviour when updating the dataSource and updating the collectionViewLayout. (As different cells are been used and they have a different height between the datasources)

1. CollectionView with segmented control that changes the datasource.
2. The first datasource has items, the second datasource has no items, the third datasource has items.
3. When switching to the empty datasource the cached items will become nil as there are no items in the section.
4. When switching to a datasource with items after this, the cached items correctly updates initially but then somewhere along the chain it invalidates the cached items returning them to the nil state. I am not sure what is causing this at the moment as the blueprint layout correctly sets this and super is always called before the cached items have been set.
5. When layoutAttibutesForItem(at indexPath: IndexPath) is called, as the cached items have been invalidated, an index out of bounds exception is caused.

implementing a safe check for the index resolves the issues, however I am not sure what's causing the cached items to become nil in the first place.

```swift
override open func layoutAttributesForItem(at indexPath: IndexPath) -> LayoutAttributes? {
    let compare: (LayoutAttributes) -> Bool
    #if os(macOS)
      compare = { indexPath > $0.indexPath! }
    #else
      compare = { indexPath > $0.indexPath }
    #endif

    guard cachedItems[safe:indexPath.section] != nil else {
        return nil
    }

    let result = binarySearch.findElement(in: cachedItems[indexPath.section],
                                          less: compare,
                                          match: { indexPath == $0.indexPath })
    return result
  }
```

```swift
subscript (safe index: Int) -> Element? {
        return index < count ? self[index] : nil
    }
```

I will add an example asap and will continue to hunt down what may be causing the cached items to become nil.

**Comment by zenangst** [comment]
@christoff-1992 keep me posted :)

**Comment by christoff-1992** [comment]
Im not sure what's going on.. I printed out some statements to ensure things where occurring in the correct order. You can see the cached items are added correctly, however during the layoutAttributesForItem* the cached items no longer exist.

> - calling prepare in BlueprintLayout - cachedItems empty
> - calling createCache in BlueprintLayout **adding 2 attributes**
> - calling createCache in BlueprintLayout completed
> - calling layoutAttributesForItem in BlueprintLayout
> - current IndexSection 0 : number of cachedItems **0**

I have managed to get the issue to replicate consistently in the following Fork of the project if you want to take a look. Just spam the fast forward button in the navigation bar, it'l happen 🙁

https://github.com/christoff-1992/Blueprints

I will continue to investigate and update if I find the root cause/ solution.

**Comment by zenangst** [comment]
@christoff-1992 fantastic that you managed to reproduce it inside an isolated environment, that is half the battle :) I'm gonna take a look when life allows. Cheers!

**Comment by zenangst** [comment]
@christoff-1992 Hey mate, So, my theory goes that the prepare method wipes the cache, like it should because it is invalid when transitioning to a new layout. However, as we try to transition and wipe the cache at the same time, there could be a slight chance that the cache is actually empty when we try to access it. I think the same crash would occur if we reduced the number of sections in the data source.

Your safeguard approach seems valid to me, mind making a PR or do you want me to make a patched version?

I was thinking about something like this:

```swift
guard indexPath.section < cachedItems.count else { return nil }
```

**Comment by christoff-1992** [comment]
@zenangst - That makes perfect sense to me, I don't mind making a pull request will do this first thing tomorrow morning. 👍 thanks for taking a look.

**Comment by zenangst** [comment]
@christoff-1992 awesome, can't wait to review it :)
I'm investigating #34 right now, I'll keep you posted on that one!

**Comment by christoff-1992** [comment]
@zenangst - Well if you need a hand with that one let me know, I wonder if it would be best to create a new layout if many changes are needed.

**Comment by zenangst** [comment]
I'll hit you up when I have a PR, I think I know what is going on with it :)
