### ISSUE TITLE
Improve the README by showing examples of the layouts

### ISSUE THREAD

**Issue by zenangst** [zenangst/Blueprints#44]
The README should get a bit of love with some screenshots showing of what kind of layouts that `Blueprints` provides out of the box.

**Comment by christoff-1992** [comment]
@zenangst - Im putting together an example application at the moment for iOS if this helps? I thought it would be useful not only fore a demo but for a common ground to investigate potential issues.

**Comment by zenangst** [comment]
@christoff-1992 sounds like a fantastic idea. Perhaps we should incorporate that into Travis.
So when we make a new PR etc, it would also build those projects just to make sure that the examples actually compile.

We should probably have examples for all three platforms, but we can start with iOS :)

**Comment by christoff-1992** [comment]
@zenangst sure that sounds like a good idea :) .. and maybe this is where I start to learn more about the OSX and TV platform 😁

**Comment by zenangst** [comment]
You should, they are tons of fun! tvOS is just a subset of UIKit so that should be pretty straightforward. macOS can be daunting at first but when you get the hang of it you can make magic. macOS is probably my favorite platform to develop for... warts and all :)

**Comment by christoff-1992** [comment]
@zenangst - Its just a platform I have not had much time to explore in my day to day ongoings, have sent you an email if your GitHub Author email is correct/an actual address.

**Comment by zenangst** [comment]
I think we could use screenshots from the example application and put those in the README 🤠
