### ISSUE TITLE
Unable to scroll past all items in the collection view. Affects both horizontal and vertical layout when using dynamic heights.

### ISSUE THREAD

**Issue by christoff-1992** [zenangst/Blueprints#48]
I know changes haven't been made to the horizontal layout to fully support dynamic heights however I thought it worth mentioning here that both are affected in slightly different ways.

**Vertical:**
If the previous columns last item has a greater height than the last item in the last column, then the scrollview bounds are pinning against the last item. This stops the user from scrolling which in turn cuts off the collection view cell.

![screenshot 2018-12-13 at 13 16 50](https://user-images.githubusercontent.com/12499390/50000365-46533880-ff91-11e8-87a3-157517504990.png)

**Horizontal:**

When scrolling around the cells disappear and re-appear, this is only an issue if items per rows is been used alongside items per column. However this may not be the intended use for a Horizontal layout and will probably be addressed in #43

**Comment by zenangst** [comment]
@christoff-1992  I think this is what the `maxY` should be used for. To set the correct content size height when the algorithm is done.

**Comment by christoff-1992** [comment]
@zenangst - It is indeed just been playing around with it, but getting some unusual behaviour where cell reusability looks to be taking/re-using the cell whilst it's still visible 🤣.. Worse the more items per row you use. May have to leave it there for today but will pick this up 😁 its been a good learning exercise around the collection view layout so far!

**Comment by christoff-1992** [comment]
We can probably close this one off now that #54 has been merged in :)

**Comment by christoff-1992** [comment]
Sure :D

**Comment by christoff-1992** [comment]
The particular issue looks fine however this is what I was describing, reckon this is related or a separate issue? If it is il close this and investigate.

![cells](https://user-images.githubusercontent.com/12499390/50217136-c86fa280-037f-11e9-810f-206614b2c2cb.gif)

**Comment by zenangst** [comment]
I wonder if that has todo with the BinarySearch constraints.
I was unable to replicate this properly when testing.
Mind sharing the settings that you are using here so that I can replicate the bug in the example?

**Comment by zenangst** [comment]
@christoff-1992  This is a bit tricky to test because it does not always appear. However, I've made a PR to fix this issue here #55 Mind taking that for a spin to see if you can still replicate the glitch?

**Comment by christoff-1992** [comment]
@zenangst sure thing will have a play around :)
