### ISSUE TITLE
OS X - Cells under vertical scroll bar

### ISSUE THREAD

**Issue by christoff-1992** [zenangst/Blueprints#66]
It appears that the cells appear under the scrollbar as this is not taken into account when the size of the item is been resolved. @zenangst - As I am no OS X developer is this by design?

**Comment by zenangst** [comment]
I think that has to do with `Show scroll bars` in `General`.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/57446/51231001-3d73cf00-1962-11e9-97e7-4ffb371921cd.png">

**Comment by christoff-1992** [comment]
Ohhh ok :) I can test the case when they're not there then I hope! .. just seems a bit strange as there look to be methods to hide the indicator. Wish I could find more documentation and examples on OS X development.

**Comment by christoff-1992** [comment]
> Closing this as this looks to be the default and expected behaviour. As you have mentioned the scrollbar visibility and style can be changed via the system settings. This may look unclean but can be easily worked around when laying out the content of the cells.
